### ISSUE TITLE
Keine Anzeige der Layerbeschreibung bei Sublayern

### ISSUE THREAD

**Issue by dpayk** [conterra/mapapps-toc-description-html#1]
bei Verwendung des Bundles dn_tocdescriptionhtml ist aufgefallen, dass die Anzeige langer Texte aus der Beschreibung des Layers (description) teilweise fehlerhaft ist. Für Root-Layer öffnet sich ein separates Fenster mit der Beschreibung, bei Sub-Layern weist das separate Fenster nur den Eintrag "undefined" auf.

Wenn ich in der App-Konfiguration die TOC Action "show-html-description" in "show-description" ändere (also das dn-Bundle deaktiviere), wird die Beschreibung für alle Layer und Sublayer korrekt angezeigt.

Berichtet hier: https://developernetwork.conterra.de/de/forum/keine-anzeige-der-layerbeschreibung-bei-sublayern

**Comment by matthiasstein** [comment]
Kannst du es bitte mit diesem Release erneut testen? https://github.com/conterra/mapapps-toc-description-html/releases/tag/1.0.4
