### ISSUE TITLE
mapapps 4.12.2: keine Verwendung von domain-bundle möglich

### ISSUE THREAD

**Issue by kbor-maschmi** [conterra/mapapps-toc-description-html#2]
In der mapapps-Version 4.12.2 führt das bundle "toc-description-html" dazu, dass Karteninhalte aus domain-bundles nicht in die App geladen werden können.

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-toc-description-html/releases/tag/1.0.4
