### ISSUE TITLE
Keine Anzeige der Layerbeschreibung bei FeatureLayers

### ISSUE THREAD

**Issue by martinlohoff** [conterra/mapapps-toc-description-html#3]
Die Anzeige der Beschreibung funktioniert leider nicht, wenn ein FeatureLayer direkt eingebunden ist (nicht via MapServer Endpoint, sondern FeatureServer). An [dieser Stelle](https://github.com/conterra/mapapps-toc-description-html/blob/7fc4d8ce38b697c565350207072e70a0227653f0/src/main/js/bundles/dn_tocdescriptionhtml/HtmlDescriptionActionDefinitionFactory.js#L44) gibt es eine Typenunterscheidung. Beim Debuggen wird hier beim FeatureLayer der Typ `layer` genutzt. Daher geht es an der Stelle nicht weiter und die Description ist vorher schon und bleibt `undefined`.

Ich hoffe um eine schnelle Lösung, da unsere aktuellen Beschreibungen durch ArcGIS Pro sehr unlesbar geworden sind (aufgrund des HTML-Formats). Daher wollen wir dieses Bundle schnellstmöglich einbinden. Noch greift ein älteres eigenes für die Anzeige. Vielen Dank vorab.

**Comment by martinlohoff** [comment]
Ich untersuche das Problem nochmal genauer. Vermutlich liegt es nicht zwingend an der markierten Zeile. Melde mich wieder.

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-toc-description-html/commit/b933c97b0b5cd45ccdb82f719085ec0596f430d6
